version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # root of the repo or adjust if your package.json lives elsewhere
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"[B
