- name: "about"
  url: "/about/"
  weight: 10
- name: "research"
  url: "/research/"
  weight: 20
- name: "gallery"
  url: "/gallery/"
  weight: 30
- name: "outreach"
  url: "/outreach/"
  weight: 40
- name: "blog"
  url: "/blog/"
  weight: 50
- name: "contact"
  url: "/contact/"
  weight: 60
