main:
  - name: "About"
    url: "/about/"
    weight: 10
    identifier: "about"
    params:
      description: "Background, Education, Professional Experience, Skills, and Languages"

  - name: "Research"
    url: "/research/"
    weight: 20
    identifier: "research"
    params:
      description: "Ongoing and Previous Research Projects, Publications, & Presentations"

  - name: "Outreach"
    url: "/outreach/"
    weight: 30
    identifier: "outreach"
    params:
      description: "Media/Press Features & Public Writing"

  - name: "Gallery"
    url: "/gallery/"
    weight: 40
    identifier: "gallery"
    params:
      description: "Photography and Art Gallery"

  - name: "Blog"
    url: "/blog/"
    weight: 50
    identifier: "blog"
    params:
      description: "Coding and Scientific Methods Blog"

  - name: "Contact"
    url: "/contact/"
    weight: 60
    identifier: "contact"
    params:
      description: "Contact Information"
