name: 'Setup Hugo Build Environment'
description: 'Reusable composite action for setting up Hugo build with caching'
inputs:
  hugo-version:
    description: 'Hugo version to install'
    required: false
    default: '0.152.1'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      if: hashFiles('package.json') != ''

    - name: Setup Node.js
      uses: actions/setup-node@v4
      if: hashFiles('package.json') != ''
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml

    - name: Install JS dependencies
      if: hashFiles('package.json') != ''
      run: pnpm install || npm install
      shell: bash

    - name: Cache Hugo build
      uses: actions/cache@v4
      with:
        path: /tmp/hugo_cache_runner/
        key: ${{ runner.os }}-hugo-deps-${{ hashFiles('**/go.mod', '**/package-lock.json', '**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-hugo-deps-

    - name: Cache Go modules
      uses: actions/cache@v4
      if: hashFiles('go.mod') != ''
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod', '**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    - name: Cache Hugo resources
      uses: actions/cache@v4
      with:
        path: resources/
        key: ${{ runner.os }}-hugo-resources-${{ hashFiles('assets/**/*', 'config/**/*', 'hugo.yaml', 'package.json') }}
        restore-keys: |
          ${{ runner.os }}-hugo-resources-

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ inputs.hugo-version }}
        extended: true
