#!/usr/bin/env bash
# Build script for Hugo site with Tailwind CSS
# Based on Hugo Blox Tailwind integration
#
# This script automates the build process that was previously run manually:
# npm install -g pnpm && hugo && hugo mod vendor && cd ./_vendor/github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind/ && pnpm i && export HB_TW_CONTENT='../../../../../../hugo_stats.json' && npx tailwindcss -i ./assets/css/styles.css --config ./tailwind.config.js -o ../../../../../../assets/dist/wc.min.css --minify --postcss && cd ../../../../../../ && rm -rf _vendor
#
# Note: Modern Hugo Blox (v0.9.0+) uses Tailwind CSS v4, which no longer requires
# the separate vendor-based build process. This script is maintained for compatibility.

set -euo pipefail

echo "=== Hugo Build Script ==="

# Ensure we're in the project root
cd "$(dirname "$0")/.."

# Check for required commands
command -v hugo >/dev/null 2>&1 || { echo "Error: hugo is not installed"; exit 1; }
command -v pnpm >/dev/null 2>&1 || { echo "Error: pnpm is not installed"; exit 1; }

# Install pnpm dependencies if package.json exists
if [ -f "package.json" ]; then
    echo "Installing pnpm dependencies..."
    pnpm install
fi

# Run Hugo to generate hugo_stats.json and build the site
echo "Running Hugo build..."
hugo --minify

# Note: The original command vendored Hugo modules and compiled Tailwind CSS separately.
# This is no longer needed with Tailwind CSS v4, which Hugo processes automatically.
# The hugo_stats.json file is generated by Hugo when build.writeStats is enabled.

echo "=== Build complete ==="
