name: Auto-enable Auto-merge

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
