name: Netlify (netlify branch)

on:
  push:
    branches: [netlify]
  pull_request:
    branches: [netlify]
  workflow_dispatch:

permissions:
  contents: read

env:
  WC_HUGO_VERSION: '0.152.1'

concurrency:
  group: netlify-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugo-deps-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugo-deps-

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: hugo --minify

      # Only verify secrets when secrets would actually be used:
      # - pushes to netlify (production)
      # - internal PRs (head repo == base repo)
      - name: Verify Netlify secrets
        if: >
          github.ref == 'refs/heads/netlify' ||
          (github.event_name == 'pull_request' &&
           github.event.pull_request.head.repo.full_name == github.repository)
        run: |
          if [ -z "${NETLIFY_AUTH_TOKEN}" ] || [ -z "${NETLIFY_SITE_ID}" ]; then
            echo "::error::Missing secrets. Set NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID in Settings → Secrets and variables → Actions."
            exit 1
          fi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # PRs → Deploy Preview (internal PRs only; forks get CI but no preview)
      - name: Deploy Preview
        if: >
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: netlify/actions/cli@v4
        with:
          args: deploy --dir=public --message="PR #${{ github.event.number }}" --json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # Pushes to netlify → Production
      - name: Deploy Production
        if: github.ref == 'refs/heads/netlify'
        uses: netlify/actions/cli@v4
        with:
          args: deploy --dir=public --prod --message="netlify @ ${{ github.sha }}" --json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
